#baseURL                          = "https://desirajusantosh.github.io/me/"  # Your domain name. Must end with "/"
baseURL = "https://desirajusantosh.github.io/santosh-blog/"
theme                            = "introduction"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites
# disqusshortname                 = ""                       # https://gohugo.io/content-management/comments
googleAnalytics                  = "G-152PCJSKRY"                       # https://gohugo.io/templates/internal/#google-analytics
canonifyURLs 			 = false
# Add relativeURLs to true
relativeURLs = true

[params]
    themeStyle                   = "dark"                 # Choose "light" or "dark"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = false                    # Turn on/off the fade-in effect
    fadeInIndex                  = true                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "desirajusantosh@gmail.com"   # E-mail address for contact section
    # customCSS                    = ["foo.css"]             # Include custom css files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "America/Los_Angeles"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "h:mm A"                # https://momentjs.com/docs/#/displaying/format/
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = true
        googlePlus               = false
        pinterest                = true

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://twitter.com/optimumprimes"
        icon  = "twitter" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://instagram.com/dsantoshb"
        icon  = "instagram" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://linkedin.com/in/desirajusantosh"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:desirajusantosh@gmail.com"  # For a direct email link, use "mailto:test@example.org".
        icon = "paper-plane" # icon name without the 'fa-'
        icon_pack = "fas"


# If you don't want to use the default menu, you can define one by yourself
# [[menu.main]]
#     name    = "Home"
#     url     = "/"
#     weight  = 0
# [[menu.main]]
#     name    = "Blog"
#     url     = "/blog/"
#     weight  = 1

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "Santosh Desiraju"
        [languages.en.params]
            description  = "Santosh Desiraju's web site"   # Max 160 characters show in search results
            # footerText   = ""                      # Text to override default footer text (markdown allowed)

